In [7]:
# 외부 라이브러리 pandas 설치
# !pip install pandas

#라이브러리 불러오기
import pandas as pd

dict_data = {
    "a" : 1,    
    "b" : 2,    
    "c" : 3,    

}

sr = pd.Series(dict_data)
print(type(sr))

<class 'pandas.Series'>

In [10]:
# 변수 sr에 저장되어 있는 시리즈 객체를 출력
print(sr)

a    1
b    2
c    3
dtype: int64

In [11]:
list_data = ['2019-01-02',3.14 , 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr)

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [ ]:
# 인덱스 배열 저장
idx = sr.index
print(idx)

# 데이터 값 배열 저장
val =  sr.values
print(val)

# 시리즈 배열을 구성하는 원소의 자료형
print(sr.dtype) # 문자열 데이터가 포함되어 있기 때문에 object

# 시리즈 배열의 크기
print(len(sr))

# 시리즈 배열의 형태
print(sr.shape) # 1차원 데이터 구조 (n,)

# 시리즈 배열의 차원
print(sr.ndim) # 배열이나 데이터 구조의 차원 수를 나타냄

RangeIndex(start=0, stop=5, step=1)
['2019-01-02' 3.14 'ABC' 100 True]
object
5
(5,)
1

In [82]:
# 원소선택

import pandas as pd

tup_data = ("영인","2010-05-01","여", True)
sr = pd.Series(tup_data, index= ["이름", "생년월일","성별","학생여부"])
srs = sr.index
val = sr.values
print(sr)
print()

print(srs)
print(val)

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

Index(['이름', '생년월일', '성별', '학생여부'], dtype='str')
['영인' '2010-05-01' '여' True]

In [83]:
# 원소선택
print(sr["이름"])
print(val[0])
print(srs[0])

영인
영인
이름

In [ ]:
sr[["생년월일","성별"]] # 두개부터는 [[ ]] 두 개 넣어야함

생년월일    2010-05-01
성별               여
dtype: object

In [41]:
print(sr)
print()
sr[0:2]

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

이름              영인
생년월일    2010-05-01
dtype: object

In [44]:
import pandas as pd

a = pd.Series()
print(a)

b = pd.Series()
print(b)

c = pd.Series("a", index = [ "a", "b", "c"])
print(c)

Series([], dtype: object)
Series([], dtype: object)
a    a
b    a
c    a
dtype: str

In [ ]:
# 데이터프레임
## 딕셔너리 -> 데이터프레임으로 변환
## pandas.DataFrame(딕셔너리)

import pandas as pd

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}


sr = pd.Series(dict_data)
print("Series")
print(sr)
print()
## 데이터 프레임으로 변환한 값
df = pd.DataFrame(dict_data)
print("DataFrame")
print(df)

Series
c0       [1, 2, 3]
c1       [4, 5, 6]
c2       [7, 8, 9]
c3    [10, 11, 12]
c4    [13, 14, 15]
dtype: object

DataFrame
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [60]:
print(type(sr))
print(type(df))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [74]:
# 행 인덱스 / 열 이름 설정
import pandas as pd

list_data = [
    [15,"남","덕영중"],
    [17,"여","수리중"]
]

df = pd.DataFrame(list_data, index = ['준서','예은'], columns = ['나이','성별','학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# 인덱스, 컬럼 이름 추출
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [71]:
# 인덱스, 컬럼 이름 변경
df.index = ["학생 1","학생 2"]
df.columns = [ "연령","남녀","소속"]

In [75]:
print(df.index)
print(df.columns)

print()

print(df)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [77]:
# df의 행 인덱스 중에서 , '준서' 를 학생 1로 '예은' 을 학생 2로 바꾸기

df = df.rename(index={"준서" : "학생 1", "예은"  : "학생 2"})
df = df.rename(columns={"나이":"연령", "성별" :"남녀","학교":"소속"})
df

      연령 남녀   소속
학생 1  15  남  덕영중
학생 2  17  여  수리중

In [89]:
# 행/열 삭제
exam_data = {
            '수학' : [90,80,70],
            '영어' : [98,89,95],
            '음악' : [85,95,100],
            '체육' : [100,90,90]
}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
print('df')
print(df)
print()
print('df.drop')

df2 = df.copy()
df2 = df2.drop('우현')
print(df2)
print()
print('df.copy')
print(df)

df
    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

df.drop
    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

df.copy
    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [91]:
df3 = df.copy()
df3.drop("영어", axis = 1) # axis = 0 -> 행 axis = 1 열

    수학   음악   체육
서준  90   85  100
우현  80   95   90
인아  70  100   90

In [93]:
df4 = df.copy()
df4.drop(["수학", "체육"], axis = "columns")

    영어   음악
서준  98   85
우현  89   95
인아  95  100

In [94]:
df5 = df.copy()
df5.drop(columns=['수학'])

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

## 행 선택

In [96]:
# 행선택
## loc 인덱서
df.loc["서준"] #서준 인덱스를 시리즈 형식으로 출력

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [103]:
print(df.iloc[0:]) # iloc는 정수형 위치 인덱스를 가지고 오는것
print()
print(df.iloc[0:2])
print()
print(df.iloc[0:1])

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100

In [106]:
label2 = df.loc[["서준","우현"]]
position2 = df.iloc[[0,1]]

print(label2)
print(position2)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

## 열 선택

In [112]:
df["수학"]

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [113]:
df["영어"]

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

In [114]:
df[["수학","영어"]]

    수학  영어
서준  90  98
우현  80  89
인아  70  95

## 원소 선택

In [144]:
exam_data = {
            '이름' : ['서준','우현','인아'],
            '수학' : [90,80,70],
            '영어' : [98,89,95],
            '음악' : [85,95,100],
            '체육' : [100,90,90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [145]:
df.loc[0]

이름     서준
수학     90
영어     98
음악     85
체육    100
Name: 0, dtype: object

In [146]:
df = df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [147]:
df.loc[['서준','우현']]

    수학  영어  음악   체육
이름
서준  90  98  85  100
우현  80  89  95   90

In [148]:
e = df.loc['서준',['음악','체육']]
g = df.loc['서준','음악':'체육']
f = df.iloc[0,[2,3]]

print(e)
print(g)
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

## 열 추가

In [149]:
df['국어'] = [10,20,30]
df

    수학  영어   음악   체육  국어
이름
서준  90  98   85  100  10
우현  80  89   95   90  20
인아  70  95  100   90  30

## 행 추가

In [151]:
df.loc["태훈"] = [100,90,90,95,100]
df

     수학  영어   음악   체육   국어
이름
서준   90  98   85  100   10
우현   80  89   95   90   20
인아   70  95  100   90   30
태훈  100  90   90   95  100

## 행, 열 위치 바꾸기

In [ ]:
# df = df.transpose()
df

      수학  영어  음악  체육  국어
이름
서준    90    98    85   100    10
우현    80    89    95    90    20
인아    70    95   100    90    30
태훈   100    90    90    95   100

In [ ]:
df['평균'] = df[['수학','영어','음악','체육']].mean(axis=1)
print(df)

      수학  영어  음악  체육  국어   평균
이름
서준    90    98    85   100    10  93.25
우현    80    89    95    90    20  88.50
인아    70    95   100    90    30  88.75
태훈   100    90    90    95   100  93.75