## 인덱스 활용

In [11]:
import pandas as pd

exam_data2 = {
            '이름' : ['서준','우현','인아'],
            '수학' : [90,80,70],
            '영어' : [98,89,95],
            '음악' : [85,95,100],
            '체육' : [100,90,90]
}

ndf = pd.DataFrame(exam_data2)
ndf

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [12]:
print(df.ndim)
print(df.shape)

2
(3, 5)

In [13]:
ndf = df.set_index('이름')
ndf

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [15]:
ndf2 = ndf.set_index('음악')
ndf2

     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90

In [16]:
ndf3 = ndf.set_index(['수학','음악'])
ndf3

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [4]:
import pandas as pd
dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index = ['r0','r1','r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [6]:
new_index = ['r0','r1','r2','r3','r4']
ndf = df.reindex(new_index, fill_value = 0)
ndf

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

## 행 인덱스 초기화 .reset_index

In [ ]:

import pandas as pd

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [10]:
ndf = df.reset_index(names = ['C00'])
print(ndf)

  C00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [11]:
ndf2 = df.reset_index(drop=True)
print(ndf2)

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

## 행 인덱스 기준으로 df 정렬 .sort_index(ascending= True,False)

In [30]:
import pandas as pd

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index=['r0','r2','r1'])
print(df)

ndf3 = df.sort_index(ascending=True)
print(ndf3)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [41]:
import pandas as pd

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index=['r0','r1','r2'])

nff2 = df.sort_index(ascending=True)
print(nff2)
ndf = df.sort_values(by='c4',ascending=False)
ndf

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [36]:
df.sort_values(by = ["c3","c4"],ascending=[False, True])

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13