In [4]:
import pandas as pd

student1 = pd.Series({
    '국어': 100,
    '영어' : 80,
    '수학' : 90
})
persentage = student1 / 200

In [5]:
persentage

국어    0.50
영어    0.40
수학    0.45
dtype: float64

In [7]:
print(type(persentage))

<class 'pandas.Series'>

In [8]:
p2 = student1 * 0.5
p2

국어    50.0
영어    40.0
수학    45.0
dtype: float64

In [11]:
## 시리즈 vs 시리즈
import pandas as pd

student1 = pd.Series({
    '국어': 100,
    '영어' : 80,
    '수학' : 90
})

student2 = pd.Series({
    '수학' : 80,
    '국어' : 90,
    '영어' : 80
})

print(student1)
print()
print(student2)

addition = student1 +student2
print()
print(type(addition))
print(addition)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [12]:
subtraction = student1 - student2
print(subtraction)

국어    10
수학    10
영어     0
dtype: int64

In [13]:
multiplication = student1 * student2
division = student1 / student2

print(multiplication)
print(division)

국어    9000
수학    7200
영어    6400
dtype: int64
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [15]:
result = pd.DataFrame([addition, subtraction, multiplication, division], index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [ ]:
## nan

import pandas as pd
import numpy as np

student1 = pd.Series({
    '국어': np.nan,
    '영어' : 80,
    '수학' : 90
})

student2 = pd.Series({
    '수학' : 80,
    '국어' : 90
})

print(student1)
print()
print(student2)

addition = student1 +student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2
print()

result = pd.DataFrame([addition, subtraction, multiplication, division], index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [19]:
## nan

import pandas as pd
import numpy as np

student1 = pd.Series({
    '국어': np.nan,
    '영어' : 80,
    '수학' : 90
})

student2 = pd.Series({
    '수학' : 80,
    '국어' : 90
})

print(student1)
print()
print(student2)

sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)
print()

result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div], index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

## 데이터프레임 연산

In [ ]:
# !pip install seaborn

In [24]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [25]:
df = titanic.loc[:,['age','fare']]
print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [26]:
addition = df + 10
print(addition.head())

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

## df vs df

In [32]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','fare']]
print(df.tail())
print()
addition = df + 10
print(addition.tail())
print()

sub = addition - df
print(sub.tail())

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [34]:
sample1 = addition.tail()
sample2 = sub.tail().fillna(0.0)

print(sample1)
print(sample2)

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75
      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [36]:
df_add = sample1.add(sample2,fill_value=0)
df_sub = sample1.sub(sample2,fill_value=0)
df_mul = sample1.mul(sample2,fill_value=0)
df_div = sample1.div(sample2,fill_value=0)

print(df_add)
print(df_sub)
print(df_mul)
print(df_div)

      age   fare
886  47.0  33.00
887  39.0  50.00
888   0.0  43.45
889  46.0  50.00
890  52.0  27.75
      age   fare
886  27.0  13.00
887  19.0  30.00
888   0.0  23.45
889  26.0  30.00
890  32.0   7.75
       age   fare
886  370.0  230.0
887  290.0  400.0
888    0.0  334.5
889  360.0  400.0
890  420.0  177.5
     age   fare
886  3.7  2.300
887  2.9  4.000
888  NaN  3.345
889  3.6  4.000
890  4.2  1.775

## filtering

In [5]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[0:9,['age','fare']]
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [8]:
df['age'] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [6]:
df[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [13]:
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [17]:
mask2 = (titanic.age < 10 )& (titanic.sex == "female")
df_female_under10 = titanic[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [24]:
mask3 = (titanic.age < 10 ) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3,['age','sex','alone']]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True